version: '3'
services: 
  hunterrankdb:
    container_name: hunterrankdb
    image: mysql:5.6
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local